name: "XiaoAI HA Bridge"
version: "1.0.9"
slug: "xiaoai_bridge"
description: "小爱音箱语音桥接 Home Assistant"
url: "https://github.com/tarynwyj/xiaoai-ha-bridge-haos"
arch:
  - amd64
stage: stable
startup: application
boot: auto
init: false

image: "ghcr.io/tarynwyj/xiaoai-ha-bridge-haos"

ports:
  47521/tcp: 47521

ports_description:
  47521/tcp: "Web 配置界面"

webui: "http://[HOST]:[PORT:47521]"

schema: false
